// Generated by tooling-split (god-files plan T1.1) — DO NOT mark with comment;
// this file is hand-maintained from now on.
//
// Single-tool slice extracted from `dap/tool.rs` as part of the
// `docs/plans/god-files-2026-07-23-plan.md` Phase 1 split (D2 strategy).

use std::sync::Arc;

use async_trait::async_trait;
use serde_json::{Value, json};

use theo_domain::error::ToolError;
#[allow(unused_imports)]
use theo_domain::tool::{
    PermissionCollector, Tool, ToolCategory, ToolContext, ToolOutput, ToolParam, ToolSchema,
};

#[allow(unused_imports)]
use crate::dap::protocol::DapResponse;
use crate::dap::session_manager::DapSessionManager;
#[allow(unused_imports)]
use crate::dap::tool_common::{
    check_response, map_session_error, parse_session_id, require_session,
};

// ---------------------------------------------------------------------------
// `debug_set_breakpoint`
// ---------------------------------------------------------------------------

/// `debug_set_breakpoint` — set line breakpoints in a file.
pub struct DebugSetBreakpointTool {
    manager: Arc<DapSessionManager>,
}

impl DebugSetBreakpointTool {
    pub fn new(manager: Arc<DapSessionManager>) -> Self {
        Self { manager }
    }
}

#[async_trait]
impl Tool for DebugSetBreakpointTool {
    fn id(&self) -> &str {
        "debug_set_breakpoint"
    }

    fn description(&self) -> &str {
        "T13.1 — Set line breakpoints in `file_path` for the active debug \
         session. Pass the FULL list of lines you want active in the file — DAP \
         setBreakpoints REPLACES every breakpoint in that source. To clear, \
         pass an empty `lines` array. The adapter returns a per-breakpoint \
         `verified` flag indicating whether the line is debuggable. Pair with \
         `debug_continue` after setting. \
         Example: debug_set_breakpoint({session_id: \"a\", file_path: \"/abs/src/main.rs\", lines: [10, 25, 42]})."
    }

    fn schema(&self) -> ToolSchema {
        ToolSchema {
            params: vec![
                ToolParam {
                    name: "session_id".into(),
                    param_type: "string".into(),
                    description: "ID of the active debug session.".into(),
                    required: true,
                },
                ToolParam {
                    name: "file_path".into(),
                    param_type: "string".into(),
                    description:
                        "Absolute path to the source file containing the \
                         breakpoints."
                            .into(),
                    required: true,
                },
                ToolParam {
                    name: "lines".into(),
                    param_type: "array".into(),
                    description:
                        "Full list of 1-based line numbers to break on in this \
                         file. DAP setBreakpoints REPLACES the previous set, so \
                         pass every line you want active. Empty array clears \
                         all breakpoints in the file."
                            .into(),
                    required: true,
                },
            ],
            input_examples: vec![json!({
                "session_id": "a",
                "file_path": "/abs/src/main.rs",
                "lines": [10, 25, 42],
            })],
        }
    }

    fn category(&self) -> ToolCategory {
        ToolCategory::Search
    }

    async fn execute(
        &self,
        args: Value,
        _ctx: &ToolContext,
        _permissions: &mut PermissionCollector,
    ) -> Result<ToolOutput, ToolError> {
        let session_id = parse_session_id(&args)?;
        let file_path = args
            .get("file_path")
            .and_then(Value::as_str)
            .ok_or_else(|| ToolError::InvalidArgs("missing string `file_path`".into()))?
            .to_string();
        let raw_lines = args
            .get("lines")
            .and_then(Value::as_array)
            .ok_or_else(|| ToolError::InvalidArgs("missing array `lines`".into()))?;
        let lines: Vec<u64> = raw_lines
            .iter()
            .map(|v| {
                v.as_u64().ok_or_else(|| {
                    ToolError::InvalidArgs(
                        "`lines` must be an array of positive integers".into(),
                    )
                })
            })
            .collect::<Result<Vec<_>, _>>()?;
        for &line in &lines {
            if line == 0 {
                return Err(ToolError::InvalidArgs(
                    "DAP line numbers are 1-based; 0 is not a valid breakpoint line".into(),
                ));
            }
        }

        let client = require_session(&self.manager, &session_id).await?;
        let breakpoints: Vec<Value> =
            lines.iter().map(|l| json!({ "line": l })).collect();
        let params = json!({
            "source": {"path": file_path},
            "breakpoints": breakpoints,
            "lines": lines, // legacy DAP field — some adapters require it
        });
        let resp = client
            .request("setBreakpoints", Some(params))
            .await
            .map_err(|e| ToolError::Execution(format!("setBreakpoints failed: {e}")))?;
        check_response(&resp, "setBreakpoints")?;
        Ok(format_set_breakpoint_output(&resp, &session_id, &file_path, &lines))
    }
}

pub(super) fn format_set_breakpoint_output(
    resp: &DapResponse,
    session_id: &str,
    file_path: &str,
    requested: &[u64],
) -> ToolOutput {
    let body_breakpoints = resp
        .body
        .as_ref()
        .and_then(|b| b.get("breakpoints"))
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let summary: Vec<Value> = body_breakpoints
        .iter()
        .enumerate()
        .map(|(i, bp)| {
            let verified = bp.get("verified").and_then(Value::as_bool).unwrap_or(false);
            let line = bp.get("line").and_then(Value::as_u64);
            let message = bp.get("message").and_then(Value::as_str);
            json!({
                "index": i,
                "requested_line": requested.get(i).copied(),
                "actual_line": line,
                "verified": verified,
                "message": message,
            })
        })
        .collect();
    let verified_count = body_breakpoints
        .iter()
        .filter(|bp| bp.get("verified").and_then(Value::as_bool).unwrap_or(false))
        .count();
    let unverified_count = body_breakpoints.len().saturating_sub(verified_count);

    let mut out = format!(
        "debug_set_breakpoint: {} requested, {} verified, {} unverified in `{file_path}` (session=`{session_id}`)\n\n",
        requested.len(),
        verified_count,
        unverified_count,
    );
    for s in &summary {
        out.push_str(&format!(
            "  - line {req:?} → actual {act:?}  verified={ver}  msg={msg:?}\n",
            req = s["requested_line"],
            act = s["actual_line"],
            ver = s["verified"],
            msg = s["message"],
        ));
    }

    ToolOutput::new(
        format!(
            "debug_set_breakpoint: {} verified / {} requested",
            verified_count,
            requested.len()
        ),
        out,
    )
    .with_metadata(json!({
        "type": "debug_set_breakpoint",
        "session_id": session_id,
        "file_path": file_path,
        "requested": requested,
        "verified_count": verified_count,
        "unverified_count": unverified_count,
        "breakpoints": summary,
    }))
}

