// Generated by tooling-split (god-files plan T1.1) — DO NOT mark with comment;
// this file is hand-maintained from now on.
//
// Single-tool slice extracted from `dap/tool.rs` as part of the
// `docs/plans/god-files-2026-07-23-plan.md` Phase 1 split (D2 strategy).

use std::sync::Arc;

use async_trait::async_trait;
use serde_json::{Value, json};

use theo_domain::error::ToolError;
#[allow(unused_imports)]
use theo_domain::tool::{
    PermissionCollector, Tool, ToolCategory, ToolContext, ToolOutput, ToolParam, ToolSchema,
};

#[allow(unused_imports)]
use crate::dap::protocol::DapResponse;
use crate::dap::session_manager::DapSessionManager;
#[allow(unused_imports)]
use crate::dap::tool_common::{
    check_response, map_session_error, parse_session_id, require_session,
};

// ---------------------------------------------------------------------------
// `debug_continue`
// ---------------------------------------------------------------------------

/// `debug_continue` — resume the debuggee after a breakpoint hit.
pub struct DebugContinueTool {
    manager: Arc<DapSessionManager>,
}

impl DebugContinueTool {
    pub fn new(manager: Arc<DapSessionManager>) -> Self {
        Self { manager }
    }
}

#[async_trait]
impl Tool for DebugContinueTool {
    fn id(&self) -> &str {
        "debug_continue"
    }

    fn description(&self) -> &str {
        "T13.1 — Resume execution of the debuggee. Pass `thread_id` to resume \
         a specific thread, or omit it to resume all threads (default). The \
         response indicates whether all threads were resumed. Typically called \
         after `debug_set_breakpoint` to start running, or after inspecting \
         state at a breakpoint hit. \
         Example: debug_continue({session_id: \"a\"})  // resume all threads."
    }

    fn schema(&self) -> ToolSchema {
        ToolSchema {
            params: vec![
                ToolParam {
                    name: "session_id".into(),
                    param_type: "string".into(),
                    description: "ID of the active debug session.".into(),
                    required: true,
                },
                ToolParam {
                    name: "thread_id".into(),
                    param_type: "integer".into(),
                    description:
                        "Optional thread to resume. When omitted, all threads \
                         are resumed."
                            .into(),
                    required: false,
                },
            ],
            input_examples: vec![json!({"session_id": "a"})],
        }
    }

    fn category(&self) -> ToolCategory {
        ToolCategory::Search
    }

    async fn execute(
        &self,
        args: Value,
        _ctx: &ToolContext,
        _permissions: &mut PermissionCollector,
    ) -> Result<ToolOutput, ToolError> {
        let session_id = parse_session_id(&args)?;
        let thread_id = args.get("thread_id").and_then(Value::as_u64);

        let client = require_session(&self.manager, &session_id).await?;
        let mut params = json!({});
        if let Some(t) = thread_id {
            params["threadId"] = json!(t);
        } else {
            // Many adapters require threadId — pass 0 with `singleThread=false`
            // when omitted, per DAP spec.
            params["threadId"] = json!(0);
            params["singleThread"] = json!(false);
        }
        let resp = client
            .request("continue", Some(params))
            .await
            .map_err(|e| ToolError::Execution(format!("continue failed: {e}")))?;
        check_response(&resp, "continue")?;
        let all_resumed = resp
            .body
            .as_ref()
            .and_then(|b| b.get("allThreadsContinued"))
            .and_then(Value::as_bool)
            .unwrap_or(thread_id.is_none());
        Ok(ToolOutput::new(
            format!(
                "debug_continue: session `{session_id}` resumed{}",
                if all_resumed { " (all threads)" } else { "" }
            ),
            format!(
                "Debugger resumed.{} Watch for `stopped` events on the \
                 next breakpoint hit; capture state with future debug_eval / \
                 debug_stack_trace tools.",
                if all_resumed { " All threads continued." } else { " Single thread continued." }
            ),
        )
        .with_metadata(json!({
            "type": "debug_continue",
            "session_id": session_id,
            "thread_id": thread_id,
            "all_threads_continued": all_resumed,
        })))
    }
}

