// Generated by tooling-split (god-files plan T1.1) — DO NOT mark with comment;
// this file is hand-maintained from now on.
//
// Single-tool slice extracted from `dap/tool.rs` as part of the
// `docs/plans/god-files-2026-07-23-plan.md` Phase 1 split (D2 strategy).

use std::sync::Arc;

use async_trait::async_trait;
use serde_json::{Value, json};

use theo_domain::error::ToolError;
#[allow(unused_imports)]
use theo_domain::tool::{
    PermissionCollector, Tool, ToolCategory, ToolContext, ToolOutput, ToolParam, ToolSchema,
};

#[allow(unused_imports)]
use crate::dap::protocol::DapResponse;
use crate::dap::session_manager::DapSessionManager;
#[allow(unused_imports)]
use crate::dap::tool_common::{
    check_response, map_session_error, parse_session_id, require_session,
};

// ---------------------------------------------------------------------------
// `debug_launch`
// ---------------------------------------------------------------------------

/// `debug_launch` — start a new debug session, spawning the adapter
/// for `language` and issuing the DAP `launch` request.
pub struct DebugLaunchTool {
    manager: Arc<DapSessionManager>,
}

impl DebugLaunchTool {
    pub fn new(manager: Arc<DapSessionManager>) -> Self {
        Self { manager }
    }
}

#[async_trait]
impl Tool for DebugLaunchTool {
    fn id(&self) -> &str {
        "debug_launch"
    }

    fn description(&self) -> &str {
        "T13.1 — Start a new debug session via DAP. Spawns the right adapter \
         for the language (lldb-vscode for rust/c/cpp, debugpy for python, dlv \
         for go, js-debug-adapter for js/ts). Pass a unique `session_id` you'll \
         reuse across debug_* calls (e.g. \"my-bin-foo\"). The `program` field \
         is the binary or script to debug; `cwd`, `args`, and `env` are \
         optional. After launch, set breakpoints with `debug_set_breakpoint`, \
         then resume with `debug_continue`. Always pair with `debug_terminate` \
         to free the adapter. \
         Example: debug_launch({session_id: \"a\", language: \"rust\", program: \"target/debug/myapp\", args: [\"--flag\"]})."
    }

    fn schema(&self) -> ToolSchema {
        ToolSchema {
            params: vec![
                ToolParam {
                    name: "session_id".into(),
                    param_type: "string".into(),
                    description:
                        "Caller-chosen identifier for this session. Reuse the \
                         same id across set_breakpoint/continue/terminate."
                            .into(),
                    required: true,
                },
                ToolParam {
                    name: "language".into(),
                    param_type: "string".into(),
                    description:
                        "Language of the debuggee — drives adapter selection \
                         (rust, c, cpp, python, go, javascript, typescript, java)."
                            .into(),
                    required: true,
                },
                ToolParam {
                    name: "program".into(),
                    param_type: "string".into(),
                    description:
                        "Absolute path to the program / script to debug."
                            .into(),
                    required: true,
                },
                ToolParam {
                    name: "args".into(),
                    param_type: "array".into(),
                    description:
                        "Optional CLI arguments passed to the debuggee."
                            .into(),
                    required: false,
                },
                ToolParam {
                    name: "cwd".into(),
                    param_type: "string".into(),
                    description:
                        "Optional working directory for the debuggee."
                            .into(),
                    required: false,
                },
                ToolParam {
                    name: "env".into(),
                    param_type: "object".into(),
                    description:
                        "Optional env vars merged with the inherited env."
                            .into(),
                    required: false,
                },
                ToolParam {
                    name: "stop_on_entry".into(),
                    param_type: "boolean".into(),
                    description:
                        "When true, the adapter pauses at the first \
                         instruction so the agent can set breakpoints \
                         BEFORE execution starts. Default: true."
                            .into(),
                    required: false,
                },
            ],
            input_examples: vec![json!({
                "session_id": "a",
                "language": "rust",
                "program": "/abs/path/target/debug/myapp",
                "args": ["--flag"],
                "stop_on_entry": true,
            })],
        }
    }

    fn category(&self) -> ToolCategory {
        ToolCategory::Search
    }

    async fn execute(
        &self,
        args: Value,
        _ctx: &ToolContext,
        _permissions: &mut PermissionCollector,
    ) -> Result<ToolOutput, ToolError> {
        let session_id = parse_session_id(&args)?;
        let language = args
            .get("language")
            .and_then(Value::as_str)
            .ok_or_else(|| ToolError::InvalidArgs("missing string `language`".into()))?
            .to_string();
        let program = args
            .get("program")
            .and_then(Value::as_str)
            .ok_or_else(|| ToolError::InvalidArgs("missing string `program`".into()))?
            .to_string();
        if program.trim().is_empty() {
            return Err(ToolError::InvalidArgs("`program` is empty".into()));
        }
        let stop_on_entry = args
            .get("stop_on_entry")
            .and_then(Value::as_bool)
            .unwrap_or(true);

        let mut launch_args = json!({
            "program": program,
            "stopOnEntry": stop_on_entry,
        });
        if let Some(prog_args) = args.get("args").cloned() {
            launch_args["args"] = prog_args;
        }
        if let Some(cwd) = args.get("cwd").cloned() {
            launch_args["cwd"] = cwd;
        }
        if let Some(env) = args.get("env").cloned() {
            launch_args["env"] = env;
        }

        let _client = self
            .manager
            .launch(&session_id, &language, launch_args)
            .await
            .map_err(map_session_error)?;

        Ok(ToolOutput::new(
            format!("debug_launch: session `{session_id}` ready"),
            format!(
                "Debug session `{session_id}` (language={language}, program={program}) is ready.\n\
                 Set breakpoints with debug_set_breakpoint, then resume with debug_continue.\n\
                 Always call debug_terminate({{session_id: \"{session_id}\"}}) when done."
            ),
        )
        .with_metadata(json!({
            "type": "debug_launch",
            "session_id": session_id,
            "language": language,
            "program": program,
            "stop_on_entry": stop_on_entry,
        })))
    }
}

