// Generated by tooling-split (god-files plan T1.1) — DO NOT mark with comment;
// this file is hand-maintained from now on.
//
// Single-tool slice extracted from `dap/tool.rs` as part of the
// `docs/plans/god-files-2026-07-23-plan.md` Phase 1 split (D2 strategy).

use std::sync::Arc;

use async_trait::async_trait;
use serde_json::{Value, json};

use theo_domain::error::ToolError;
#[allow(unused_imports)]
use theo_domain::tool::{
    PermissionCollector, Tool, ToolCategory, ToolContext, ToolOutput, ToolParam, ToolSchema,
};

#[allow(unused_imports)]
use crate::dap::protocol::DapResponse;
use crate::dap::session_manager::DapSessionManager;
#[allow(unused_imports)]
use crate::dap::tool_common::{
    check_response, map_session_error, parse_session_id, require_session,
};

// ---------------------------------------------------------------------------
// `debug_scopes`
// ---------------------------------------------------------------------------

/// `debug_scopes` — list variable scopes (locals, globals, etc.) for a frame.
pub struct DebugScopesTool {
    manager: Arc<DapSessionManager>,
}

impl DebugScopesTool {
    pub fn new(manager: Arc<DapSessionManager>) -> Self {
        Self { manager }
    }
}

#[async_trait]
impl Tool for DebugScopesTool {
    fn id(&self) -> &str {
        "debug_scopes"
    }

    fn description(&self) -> &str {
        "T13.1 — List variable scopes for a stack frame (DAP `scopes`). \
         Each scope carries its OWN variablesReference, which `debug_variables` \
         can drill. Typical scopes: \"Locals\", \"Globals\", \"Arguments\". \
         Use this AFTER `debug_stack_trace` (which gave you frame_id) and \
         BEFORE `debug_variables` (which descends into a scope). \
         Example: debug_scopes({session_id: \"a\", frame_id: 1000})."
    }

    fn schema(&self) -> ToolSchema {
        ToolSchema {
            params: vec![
                ToolParam {
                    name: "session_id".into(),
                    param_type: "string".into(),
                    description: "ID of the active debug session.".into(),
                    required: true,
                },
                ToolParam {
                    name: "frame_id".into(),
                    param_type: "integer".into(),
                    description:
                        "Frame to fetch scopes for. Get from debug_stack_trace."
                            .into(),
                    required: true,
                },
            ],
            input_examples: vec![json!({"session_id": "a", "frame_id": 1000})],
        }
    }

    fn category(&self) -> ToolCategory {
        ToolCategory::Search
    }

    async fn execute(
        &self,
        args: Value,
        _ctx: &ToolContext,
        _permissions: &mut PermissionCollector,
    ) -> Result<ToolOutput, ToolError> {
        let session_id = parse_session_id(&args)?;
        let frame_id = args
            .get("frame_id")
            .and_then(Value::as_u64)
            .ok_or_else(|| {
                ToolError::InvalidArgs("missing integer `frame_id`".into())
            })?;

        let client = require_session(&self.manager, &session_id).await?;
        let resp = client
            .request("scopes", Some(json!({"frameId": frame_id})))
            .await
            .map_err(|e| ToolError::Execution(format!("scopes failed: {e}")))?;
        check_response(&resp, "scopes")?;
        Ok(format_scopes_output(&resp, &session_id, frame_id))
    }
}

pub(super) fn format_scopes_output(
    resp: &DapResponse,
    session_id: &str,
    frame_id: u64,
) -> ToolOutput {
    let scopes = resp
        .body
        .as_ref()
        .and_then(|b| b.get("scopes"))
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let summary: Vec<Value> = scopes
        .iter()
        .map(|s| {
            json!({
                "name": s.get("name").and_then(Value::as_str),
                "presentation_hint": s.get("presentationHint").and_then(Value::as_str),
                "variables_reference": s
                    .get("variablesReference")
                    .and_then(Value::as_u64)
                    .unwrap_or(0),
                "expensive": s.get("expensive").and_then(Value::as_bool).unwrap_or(false),
            })
        })
        .collect();

    let mut out = format!(
        "debug_scopes: {} scope(s) for frame {frame_id} (session=`{session_id}`)\n\n",
        scopes.len(),
    );
    for s in &summary {
        let drill = if s["variables_reference"].as_u64().unwrap_or(0) > 0 {
            format!("  [drill: {}]", s["variables_reference"])
        } else {
            String::new()
        };
        let expensive = if s["expensive"].as_bool().unwrap_or(false) {
            "  (EXPENSIVE — fetches over network)"
        } else {
            ""
        };
        out.push_str(&format!(
            "  {name}{hint}{drill}{expensive}\n",
            name = s["name"].as_str().unwrap_or("(unnamed)"),
            hint = match s["presentation_hint"].as_str() {
                Some(h) => format!("  ({h})"),
                None => String::new(),
            },
            drill = drill,
            expensive = expensive,
        ));
    }
    if scopes.is_empty() {
        out.push_str(
            "(no scopes returned — frame may be invalid or thread not stopped)\n",
        );
    }

    ToolOutput::new(
        format!("debug_scopes: {} scope(s) for frame {frame_id}", scopes.len()),
        out,
    )
    .with_metadata(json!({
        "type": "debug_scopes",
        "session_id": session_id,
        "frame_id": frame_id,
        "scope_count": scopes.len(),
        "scopes": summary,
    }))
}

