// Generated by tooling-split (god-files plan T1.1) — DO NOT mark with comment;
// this file is hand-maintained from now on.
//
// Single-tool slice extracted from `dap/tool.rs` as part of the
// `docs/plans/god-files-2026-07-23-plan.md` Phase 1 split (D2 strategy).

use std::sync::Arc;

use async_trait::async_trait;
use serde_json::{Value, json};

use theo_domain::error::ToolError;
#[allow(unused_imports)]
use theo_domain::tool::{
    PermissionCollector, Tool, ToolCategory, ToolContext, ToolOutput, ToolParam, ToolSchema,
};

#[allow(unused_imports)]
use crate::dap::protocol::DapResponse;
use crate::dap::session_manager::DapSessionManager;
#[allow(unused_imports)]
use crate::dap::tool_common::{
    check_response, map_session_error, parse_session_id, require_session,
};

// ---------------------------------------------------------------------------
// `debug_stack_trace`
// ---------------------------------------------------------------------------

/// `debug_stack_trace` — fetch the call stack for a thread.
pub struct DebugStackTraceTool {
    manager: Arc<DapSessionManager>,
}

impl DebugStackTraceTool {
    pub fn new(manager: Arc<DapSessionManager>) -> Self {
        Self { manager }
    }
}

#[async_trait]
impl Tool for DebugStackTraceTool {
    fn id(&self) -> &str {
        "debug_stack_trace"
    }

    fn description(&self) -> &str {
        "T13.1 — Fetch the call stack for `thread_id` (DAP `stackTrace`). \
         Use after a `stopped` event to see where execution paused. \
         `start_frame` (default 0) skips that many top frames; `levels` \
         (default 20) caps the slice. Each frame carries an `id` you can pass \
         to `debug_eval(frame_id)` or future `debug_scopes` to inspect locals \
         at that level. \
         Example: debug_stack_trace({session_id: \"a\", thread_id: 1})."
    }

    fn schema(&self) -> ToolSchema {
        ToolSchema {
            params: vec![
                ToolParam {
                    name: "session_id".into(),
                    param_type: "string".into(),
                    description: "ID of the active debug session.".into(),
                    required: true,
                },
                ToolParam {
                    name: "thread_id".into(),
                    param_type: "integer".into(),
                    description:
                        "Thread to fetch the stack for. Get it from a \
                         `stopped` event or future debug_threads tool."
                            .into(),
                    required: true,
                },
                ToolParam {
                    name: "start_frame".into(),
                    param_type: "integer".into(),
                    description: "Skip this many top frames. Default 0.".into(),
                    required: false,
                },
                ToolParam {
                    name: "levels".into(),
                    param_type: "integer".into(),
                    description:
                        "Cap on frames returned. Default 20 — increase to see \
                         deeper stacks. 0 = adapter default (often unlimited)."
                            .into(),
                    required: false,
                },
            ],
            input_examples: vec![
                json!({"session_id": "a", "thread_id": 1}),
                json!({"session_id": "a", "thread_id": 1, "start_frame": 5, "levels": 10}),
            ],
        }
    }

    fn category(&self) -> ToolCategory {
        ToolCategory::Search
    }

    async fn execute(
        &self,
        args: Value,
        _ctx: &ToolContext,
        _permissions: &mut PermissionCollector,
    ) -> Result<ToolOutput, ToolError> {
        let session_id = parse_session_id(&args)?;
        let thread_id = args
            .get("thread_id")
            .and_then(Value::as_u64)
            .ok_or_else(|| {
                ToolError::InvalidArgs("missing integer `thread_id`".into())
            })?;
        let start_frame = args
            .get("start_frame")
            .and_then(Value::as_u64)
            .unwrap_or(0);
        let levels = args.get("levels").and_then(Value::as_u64).unwrap_or(20);

        let client = require_session(&self.manager, &session_id).await?;
        let mut params = json!({
            "threadId": thread_id,
            "startFrame": start_frame,
        });
        if levels > 0 {
            params["levels"] = json!(levels);
        }
        let resp = client
            .request("stackTrace", Some(params))
            .await
            .map_err(|e| ToolError::Execution(format!("stackTrace failed: {e}")))?;
        check_response(&resp, "stackTrace")?;
        Ok(format_stack_trace_output(
            &resp,
            &session_id,
            thread_id,
            start_frame,
            levels,
        ))
    }
}

pub(super) fn format_stack_trace_output(
    resp: &DapResponse,
    session_id: &str,
    thread_id: u64,
    start_frame: u64,
    levels: u64,
) -> ToolOutput {
    let body = resp.body.as_ref();
    let frames = body
        .and_then(|b| b.get("stackFrames"))
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let total_frames = body
        .and_then(|b| b.get("totalFrames"))
        .and_then(Value::as_u64);

    let summary: Vec<Value> = frames
        .iter()
        .map(|f| {
            json!({
                "id": f.get("id").and_then(Value::as_u64),
                "name": f.get("name").and_then(Value::as_str),
                "source_path": f
                    .get("source")
                    .and_then(|s| s.get("path"))
                    .and_then(Value::as_str),
                "line": f.get("line").and_then(Value::as_u64),
                "column": f.get("column").and_then(Value::as_u64),
            })
        })
        .collect();

    let mut out = format!(
        "debug_stack_trace: {} frame(s){} (session=`{session_id}`, thread={thread_id})\n\n",
        frames.len(),
        match total_frames {
            Some(n) => format!(" of {n} total"),
            None => String::new(),
        }
    );
    for (i, f) in summary.iter().enumerate() {
        let frame_num = start_frame + i as u64;
        out.push_str(&format!(
            "  #{frame_num}  id={id}  {name}  {path}:{line}:{col}\n",
            id = f["id"],
            name = f["name"].as_str().unwrap_or("(no name)"),
            path = f["source_path"].as_str().unwrap_or("(no source)"),
            line = f["line"],
            col = f["column"],
        ));
    }
    if frames.is_empty() {
        out.push_str("(no frames returned — thread may not be in a stopped state)\n");
    }

    ToolOutput::new(
        format!(
            "debug_stack_trace: {} frame(s) (thread {thread_id})",
            frames.len()
        ),
        out,
    )
    .with_metadata(json!({
        "type": "debug_stack_trace",
        "session_id": session_id,
        "thread_id": thread_id,
        "start_frame": start_frame,
        "levels": levels,
        "total_frames": total_frames,
        "frame_count": frames.len(),
        "frames": summary,
    }))
}

