// Generated by tooling-split (god-files plan T1.1) — DO NOT mark with comment;
// this file is hand-maintained from now on.
//
// Single-tool slice extracted from `dap/tool.rs` as part of the
// `docs/plans/god-files-2026-07-23-plan.md` Phase 1 split (D2 strategy).

use std::sync::Arc;

use async_trait::async_trait;
use serde_json::{Value, json};

use theo_domain::error::ToolError;
#[allow(unused_imports)]
use theo_domain::tool::{
    PermissionCollector, Tool, ToolCategory, ToolContext, ToolOutput, ToolParam, ToolSchema,
};

#[allow(unused_imports)]
use crate::dap::protocol::DapResponse;
use crate::dap::session_manager::DapSessionManager;
#[allow(unused_imports)]
use crate::dap::tool_common::{
    check_response, map_session_error, parse_session_id, require_session,
};

// ---------------------------------------------------------------------------
// `debug_status`
// ---------------------------------------------------------------------------

/// `debug_status` — report which DAP adapters are discoverable on
/// PATH and which active sessions exist. Lets the agent decide
/// whether to debug at all OR fall back to print-debugging /
/// reading test output.
pub struct DebugStatusTool {
    manager: Arc<DapSessionManager>,
}

impl DebugStatusTool {
    pub fn new(manager: Arc<DapSessionManager>) -> Self {
        Self { manager }
    }
}

#[async_trait]
impl Tool for DebugStatusTool {
    fn id(&self) -> &str {
        "debug_status"
    }

    fn description(&self) -> &str {
        "T13.1 — Report which DAP adapters are discoverable on PATH \
         (lldb-vscode for rust/c/cpp; debugpy for python; dlv for go; \
         js-debug-adapter for js/ts; java-debug-server for java) AND list \
         the currently active debug sessions (id + language). Use BEFORE \
         `debug_launch` to know whether the language has an installed \
         adapter; when none, fall back to print-debugging or reading test \
         output. \
         Example: debug_status({})."
    }

    fn schema(&self) -> ToolSchema {
        ToolSchema {
            params: vec![],
            input_examples: vec![json!({})],
        }
    }

    fn category(&self) -> ToolCategory {
        ToolCategory::Search
    }

    async fn execute(
        &self,
        _args: Value,
        _ctx: &ToolContext,
        _permissions: &mut PermissionCollector,
    ) -> Result<ToolOutput, ToolError> {
        let mut languages = self.manager.supported_languages().await;
        languages.sort();

        let active = self.manager.active_sessions().await;
        let mut active_sorted = active.clone();
        active_sorted.sort();

        let lang_count = languages.len();
        let active_count = active_sorted.len();
        let metadata = json!({
            "type": "debug_status",
            "supported_language_count": lang_count,
            "supported_languages": languages,
            "active_session_count": active_count,
            "active_session_ids": active_sorted,
        });

        let mut output = String::new();
        if languages.is_empty() {
            output.push_str(
                "No DAP adapters discovered on PATH. Install one for the \
                 languages you debug (lldb-vscode for rust/c/cpp, debugpy \
                 for python, dlv for go, js-debug-adapter for js/ts) or \
                 fall back to print-debugging.\n",
            );
        } else {
            output.push_str(&format!(
                "{lang_count} language(s) routable to an installed DAP \
                 adapter: {}.\n",
                languages.join(", ")
            ));
        }
        if active_sorted.is_empty() {
            output.push_str(
                "No active debug sessions. Open one with `debug_launch`.",
            );
        } else {
            output.push_str(&format!(
                "{active_count} active debug session(s): {}. Use the id \
                 with debug_set_breakpoint / debug_continue / debug_step / \
                 debug_eval / debug_terminate.",
                active_sorted.join(", "),
            ));
        }

        Ok(ToolOutput::new(
            format!(
                "debug_status: {lang_count} language(s) routable, \
                 {active_count} active session(s)"
            ),
            output,
        )
        .with_metadata(metadata))
    }
}

