// Generated by tooling-split (god-files plan T1.1) — DO NOT mark with comment;
// this file is hand-maintained from now on.
//
// Single-tool slice extracted from `dap/tool.rs` as part of the
// `docs/plans/god-files-2026-07-23-plan.md` Phase 1 split (D2 strategy).

use std::sync::Arc;

use async_trait::async_trait;
use serde_json::{Value, json};

use theo_domain::error::ToolError;
#[allow(unused_imports)]
use theo_domain::tool::{
    PermissionCollector, Tool, ToolCategory, ToolContext, ToolOutput, ToolParam, ToolSchema,
};

#[allow(unused_imports)]
use crate::dap::protocol::DapResponse;
use crate::dap::session_manager::DapSessionManager;
#[allow(unused_imports)]
use crate::dap::tool_common::{
    check_response, map_session_error, parse_session_id, require_session,
};

// ---------------------------------------------------------------------------
// `debug_step`
// ---------------------------------------------------------------------------

/// `debug_step` — single-step the debuggee. Three step kinds:
///   - `over` (DAP `next`):    step the current line, skipping calls.
///   - `in`   (DAP `stepIn`):  step into the next function call.
///   - `out`  (DAP `stepOut`): run until the current frame returns.
pub struct DebugStepTool {
    manager: Arc<DapSessionManager>,
}

impl DebugStepTool {
    pub fn new(manager: Arc<DapSessionManager>) -> Self {
        Self { manager }
    }
}

#[async_trait]
impl Tool for DebugStepTool {
    fn id(&self) -> &str {
        "debug_step"
    }

    fn description(&self) -> &str {
        "T13.1 — Single-step the debuggee. `kind` selects the step style: \
         \"over\" (DAP `next`, skip calls), \"in\" (DAP `stepIn`, descend into \
         the next call), \"out\" (DAP `stepOut`, run until current frame \
         returns). `thread_id` IS REQUIRED by DAP for stepping (unlike \
         continue) — get it from the most recent `stopped` event or DAP \
         `threads` request. Watch for the next `stopped` event after stepping. \
         Example: debug_step({session_id: \"a\", kind: \"over\", thread_id: 1})."
    }

    fn schema(&self) -> ToolSchema {
        ToolSchema {
            params: vec![
                ToolParam {
                    name: "session_id".into(),
                    param_type: "string".into(),
                    description: "ID of the active debug session.".into(),
                    required: true,
                },
                ToolParam {
                    name: "kind".into(),
                    param_type: "string".into(),
                    description:
                        "One of: `over` (step skipping function calls), \
                         `in` (step into the next call), `out` (run until \
                         current frame returns)."
                            .into(),
                    required: true,
                },
                ToolParam {
                    name: "thread_id".into(),
                    param_type: "integer".into(),
                    description:
                        "Thread to step. Required by DAP — get it from the \
                         most recent `stopped` event."
                            .into(),
                    required: true,
                },
            ],
            input_examples: vec![
                json!({"session_id": "a", "kind": "over", "thread_id": 1}),
                json!({"session_id": "a", "kind": "in", "thread_id": 1}),
                json!({"session_id": "a", "kind": "out", "thread_id": 1}),
            ],
        }
    }

    fn category(&self) -> ToolCategory {
        ToolCategory::Search
    }

    async fn execute(
        &self,
        args: Value,
        _ctx: &ToolContext,
        _permissions: &mut PermissionCollector,
    ) -> Result<ToolOutput, ToolError> {
        let session_id = parse_session_id(&args)?;
        let kind = args
            .get("kind")
            .and_then(Value::as_str)
            .ok_or_else(|| ToolError::InvalidArgs("missing string `kind`".into()))?;
        let dap_command = match kind {
            "over" => "next",
            "in" => "stepIn",
            "out" => "stepOut",
            other => {
                return Err(ToolError::InvalidArgs(format!(
                    "`kind` must be one of `over`, `in`, `out` (got `{other}`)"
                )));
            }
        };
        let thread_id = args
            .get("thread_id")
            .and_then(Value::as_u64)
            .ok_or_else(|| {
                ToolError::InvalidArgs(
                    "missing integer `thread_id` — DAP step requires it (get it from the most recent stopped event)"
                        .into(),
                )
            })?;

        let client = require_session(&self.manager, &session_id).await?;
        let resp = client
            .request(dap_command, Some(json!({"threadId": thread_id})))
            .await
            .map_err(|e| ToolError::Execution(format!("{dap_command} failed: {e}")))?;
        check_response(&resp, dap_command)?;
        Ok(ToolOutput::new(
            format!(
                "debug_step: session `{session_id}` stepped {kind} (thread {thread_id})"
            ),
            format!(
                "Step {kind} executed via DAP `{dap_command}`. Watch for the \
                 next `stopped` event to inspect new state."
            ),
        )
        .with_metadata(json!({
            "type": "debug_step",
            "session_id": session_id,
            "kind": kind,
            "dap_command": dap_command,
            "thread_id": thread_id,
        })))
    }
}

