// Generated by tooling-split (god-files plan T1.1) — DO NOT mark with comment;
// this file is hand-maintained from now on.
//
// Single-tool slice extracted from `dap/tool.rs` as part of the
// `docs/plans/god-files-2026-07-23-plan.md` Phase 1 split (D2 strategy).

use std::sync::Arc;

use async_trait::async_trait;
use serde_json::{Value, json};

use theo_domain::error::ToolError;
#[allow(unused_imports)]
use theo_domain::tool::{
    PermissionCollector, Tool, ToolCategory, ToolContext, ToolOutput, ToolParam, ToolSchema,
};

#[allow(unused_imports)]
use crate::dap::protocol::DapResponse;
use crate::dap::session_manager::DapSessionManager;
#[allow(unused_imports)]
use crate::dap::tool_common::{
    check_response, map_session_error, parse_session_id, require_session,
};

// ---------------------------------------------------------------------------
// `debug_terminate`
// ---------------------------------------------------------------------------

/// `debug_terminate` — close a debug session and free the adapter.
pub struct DebugTerminateTool {
    manager: Arc<DapSessionManager>,
}

impl DebugTerminateTool {
    pub fn new(manager: Arc<DapSessionManager>) -> Self {
        Self { manager }
    }
}

#[async_trait]
impl Tool for DebugTerminateTool {
    fn id(&self) -> &str {
        "debug_terminate"
    }

    fn description(&self) -> &str {
        "T13.1 — End a debug session. Drops the cached DapClient, killing the \
         adapter via kill_on_drop. Idempotent: terminating an unknown session_id \
         returns success with `was_active=false`. Always pair with \
         `debug_launch` to avoid leaking adapter processes between agent runs. \
         Example: debug_terminate({session_id: \"a\"})."
    }

    fn schema(&self) -> ToolSchema {
        ToolSchema {
            params: vec![ToolParam {
                name: "session_id".into(),
                param_type: "string".into(),
                description:
                    "ID of the session to terminate. Idempotent — unknown \
                     ids return success."
                        .into(),
                required: true,
            }],
            input_examples: vec![json!({"session_id": "a"})],
        }
    }

    fn category(&self) -> ToolCategory {
        ToolCategory::Search
    }

    async fn execute(
        &self,
        args: Value,
        _ctx: &ToolContext,
        _permissions: &mut PermissionCollector,
    ) -> Result<ToolOutput, ToolError> {
        let session_id = parse_session_id(&args)?;
        let was_active = self.manager.terminate(&session_id).await;
        let title = if was_active {
            format!("debug_terminate: session `{session_id}` terminated")
        } else {
            format!(
                "debug_terminate: no active session `{session_id}` (no-op)"
            )
        };
        Ok(ToolOutput::new(
            title,
            if was_active {
                format!(
                    "Debug session `{session_id}` ended. The adapter process \
                     was killed via kill_on_drop. Safe to re-launch with the \
                     same id."
                )
            } else {
                format!(
                    "No session `{session_id}` was active — nothing to do. \
                     terminate() is idempotent."
                )
            },
        )
        .with_metadata(json!({
            "type": "debug_terminate",
            "session_id": session_id,
            "was_active": was_active,
        })))
    }
}

// Tests for all 11 debug_* tools live in the sibling `tool_tests.rs`
// file, attached to the dap module via `#[path = "tool_tests.rs"]`
// in dap/mod.rs (T1.1 of god-files-2026-07-23-plan.md).
