// Generated by tooling-split (god-files plan T1.1) — DO NOT mark with comment;
// this file is hand-maintained from now on.
//
// Single-tool slice extracted from `dap/tool.rs` as part of the
// `docs/plans/god-files-2026-07-23-plan.md` Phase 1 split (D2 strategy).

use std::sync::Arc;

use async_trait::async_trait;
use serde_json::{Value, json};

use theo_domain::error::ToolError;
#[allow(unused_imports)]
use theo_domain::tool::{
    PermissionCollector, Tool, ToolCategory, ToolContext, ToolOutput, ToolParam, ToolSchema,
};

#[allow(unused_imports)]
use crate::dap::protocol::DapResponse;
use crate::dap::session_manager::DapSessionManager;
#[allow(unused_imports)]
use crate::dap::tool_common::{
    check_response, map_session_error, parse_session_id, require_session,
};

// ---------------------------------------------------------------------------
// `debug_threads`
// ---------------------------------------------------------------------------

/// `debug_threads` — list every thread in the debuggee.
pub struct DebugThreadsTool {
    manager: Arc<DapSessionManager>,
}

impl DebugThreadsTool {
    pub fn new(manager: Arc<DapSessionManager>) -> Self {
        Self { manager }
    }
}

#[async_trait]
impl Tool for DebugThreadsTool {
    fn id(&self) -> &str {
        "debug_threads"
    }

    fn description(&self) -> &str {
        "T13.1 — List every thread in the debuggee (DAP `threads`). Useful \
         when a `stopped` event didn't carry thread_id, or when you need \
         to step through multi-threaded code and pick which thread to step. \
         Each thread has {id, name}. \
         Example: debug_threads({session_id: \"a\"})."
    }

    fn schema(&self) -> ToolSchema {
        ToolSchema {
            params: vec![ToolParam {
                name: "session_id".into(),
                param_type: "string".into(),
                description: "ID of the active debug session.".into(),
                required: true,
            }],
            input_examples: vec![json!({"session_id": "a"})],
        }
    }

    fn category(&self) -> ToolCategory {
        ToolCategory::Search
    }

    async fn execute(
        &self,
        args: Value,
        _ctx: &ToolContext,
        _permissions: &mut PermissionCollector,
    ) -> Result<ToolOutput, ToolError> {
        let session_id = parse_session_id(&args)?;
        let client = require_session(&self.manager, &session_id).await?;
        let resp = client
            .request("threads", None)
            .await
            .map_err(|e| ToolError::Execution(format!("threads failed: {e}")))?;
        check_response(&resp, "threads")?;
        Ok(format_threads_output(&resp, &session_id))
    }
}

pub(super) fn format_threads_output(resp: &DapResponse, session_id: &str) -> ToolOutput {
    let threads = resp
        .body
        .as_ref()
        .and_then(|b| b.get("threads"))
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let summary: Vec<Value> = threads
        .iter()
        .map(|t| {
            json!({
                "id": t.get("id").and_then(Value::as_u64),
                "name": t.get("name").and_then(Value::as_str),
            })
        })
        .collect();

    let mut out = format!(
        "debug_threads: {} thread(s) (session=`{session_id}`)\n\n",
        threads.len(),
    );
    for t in &summary {
        out.push_str(&format!(
            "  id={id}  {name}\n",
            id = t["id"],
            name = t["name"].as_str().unwrap_or("(no name)"),
        ));
    }
    if threads.is_empty() {
        out.push_str(
            "(no threads — adapter may have terminated; call debug_terminate \
             and re-launch)\n",
        );
    }

    ToolOutput::new(
        format!("debug_threads: {} thread(s)", threads.len()),
        out,
    )
    .with_metadata(json!({
        "type": "debug_threads",
        "session_id": session_id,
        "thread_count": threads.len(),
        "threads": summary,
    }))
}

