// Generated by tooling-split (god-files plan T1.1) — DO NOT mark with comment;
// this file is hand-maintained from now on.
//
// Single-tool slice extracted from `dap/tool.rs` as part of the
// `docs/plans/god-files-2026-07-23-plan.md` Phase 1 split (D2 strategy).

use std::sync::Arc;

use async_trait::async_trait;
use serde_json::{Value, json};

use theo_domain::error::ToolError;
#[allow(unused_imports)]
use theo_domain::tool::{
    PermissionCollector, Tool, ToolCategory, ToolContext, ToolOutput, ToolParam, ToolSchema,
};

#[allow(unused_imports)]
use crate::dap::protocol::DapResponse;
use crate::dap::session_manager::DapSessionManager;
#[allow(unused_imports)]
use crate::dap::tool_common::{
    check_response, map_session_error, parse_session_id, require_session,
};

// ---------------------------------------------------------------------------
// `debug_variables`
// ---------------------------------------------------------------------------

/// `debug_variables` — drill into a variables container.
pub struct DebugVariablesTool {
    manager: Arc<DapSessionManager>,
}

impl DebugVariablesTool {
    pub fn new(manager: Arc<DapSessionManager>) -> Self {
        Self { manager }
    }
}

#[async_trait]
impl Tool for DebugVariablesTool {
    fn id(&self) -> &str {
        "debug_variables"
    }

    fn description(&self) -> &str {
        "T13.1 — List children of a `variables_reference` (DAP `variables`). \
         The reference comes from `debug_eval` (when the result is structured: \
         struct, vec, hashmap), or from a future `debug_scopes` tool. \
         Returns each child's name, value preview, type, and its OWN \
         variables_reference (so the agent can recursively descend). Optional \
         `start` + `count` paginate large containers (e.g. a Vec<T> with \
         100k items). \
         Example: debug_variables({session_id: \"a\", variables_reference: 7})."
    }

    fn schema(&self) -> ToolSchema {
        ToolSchema {
            params: vec![
                ToolParam {
                    name: "session_id".into(),
                    param_type: "string".into(),
                    description: "ID of the active debug session.".into(),
                    required: true,
                },
                ToolParam {
                    name: "variables_reference".into(),
                    param_type: "integer".into(),
                    description:
                        "Container reference from a previous `debug_eval` or \
                         `debug_scopes` response. MUST be > 0; references \
                         marked as 0 in the parent are non-drillable scalars."
                            .into(),
                    required: true,
                },
                ToolParam {
                    name: "start".into(),
                    param_type: "integer".into(),
                    description:
                        "Index to start at when paginating. Default 0."
                            .into(),
                    required: false,
                },
                ToolParam {
                    name: "count".into(),
                    param_type: "integer".into(),
                    description:
                        "Max children to return. Default 100. 0 = adapter \
                         default (often unlimited — risky for huge containers)."
                            .into(),
                    required: false,
                },
                ToolParam {
                    name: "filter".into(),
                    param_type: "string".into(),
                    description:
                        "DAP child filter: `indexed` (array entries) or \
                         `named` (struct fields). Omit to get both."
                            .into(),
                    required: false,
                },
            ],
            input_examples: vec![
                json!({"session_id": "a", "variables_reference": 7}),
                json!({"session_id": "a", "variables_reference": 7, "start": 0, "count": 50}),
            ],
        }
    }

    fn category(&self) -> ToolCategory {
        ToolCategory::Search
    }

    async fn execute(
        &self,
        args: Value,
        _ctx: &ToolContext,
        _permissions: &mut PermissionCollector,
    ) -> Result<ToolOutput, ToolError> {
        let session_id = parse_session_id(&args)?;
        let var_ref = args
            .get("variables_reference")
            .and_then(Value::as_u64)
            .ok_or_else(|| {
                ToolError::InvalidArgs(
                    "missing integer `variables_reference`".into(),
                )
            })?;
        if var_ref == 0 {
            return Err(ToolError::InvalidArgs(
                "`variables_reference` must be > 0; reference == 0 marks \
                 a scalar value with no children to drill into"
                    .into(),
            ));
        }
        let start = args.get("start").and_then(Value::as_u64).unwrap_or(0);
        let count = args.get("count").and_then(Value::as_u64).unwrap_or(100);
        let filter = args.get("filter").and_then(Value::as_str).map(str::to_string);
        if let Some(ref f) = filter
            && !["indexed", "named"].contains(&f.as_str())
        {
            return Err(ToolError::InvalidArgs(format!(
                "`filter` must be `indexed` or `named` (got `{f}`)"
            )));
        }

        let client = require_session(&self.manager, &session_id).await?;
        let mut params = json!({
            "variablesReference": var_ref,
            "start": start,
        });
        if count > 0 {
            params["count"] = json!(count);
        }
        if let Some(ref f) = filter {
            params["filter"] = json!(f);
        }
        let resp = client
            .request("variables", Some(params))
            .await
            .map_err(|e| ToolError::Execution(format!("variables failed: {e}")))?;
        check_response(&resp, "variables")?;
        Ok(format_variables_output(
            &resp,
            &session_id,
            var_ref,
            start,
            count,
            filter.as_deref(),
        ))
    }
}

pub(super) fn format_variables_output(
    resp: &DapResponse,
    session_id: &str,
    variables_reference: u64,
    start: u64,
    count: u64,
    filter: Option<&str>,
) -> ToolOutput {
    let vars = resp
        .body
        .as_ref()
        .and_then(|b| b.get("variables"))
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let summary: Vec<Value> = vars
        .iter()
        .map(|v| {
            json!({
                "name": v.get("name").and_then(Value::as_str),
                "value": v.get("value").and_then(Value::as_str),
                "type": v.get("type").and_then(Value::as_str),
                "variables_reference": v
                    .get("variablesReference")
                    .and_then(Value::as_u64)
                    .unwrap_or(0),
                "evaluate_name": v.get("evaluateName").and_then(Value::as_str),
            })
        })
        .collect();

    let drillable_count = summary
        .iter()
        .filter(|s| s["variables_reference"].as_u64().unwrap_or(0) > 0)
        .count();

    let mut out = format!(
        "debug_variables: {} child(ren), {} drillable (session=`{session_id}`, ref={variables_reference})\n\n",
        summary.len(),
        drillable_count,
    );
    for s in &summary {
        let drill_hint = if s["variables_reference"].as_u64().unwrap_or(0) > 0 {
            format!("  [drill: {}]", s["variables_reference"])
        } else {
            String::new()
        };
        out.push_str(&format!(
            "  {name} = {value}{ty}{drill}\n",
            name = s["name"].as_str().unwrap_or("(unnamed)"),
            value = s["value"].as_str().unwrap_or("?"),
            ty = match s["type"].as_str() {
                Some(t) => format!("  : {t}"),
                None => String::new(),
            },
            drill = drill_hint,
        ));
    }

    ToolOutput::new(
        format!(
            "debug_variables: {} child(ren), {} drillable",
            summary.len(),
            drillable_count
        ),
        out,
    )
    .with_metadata(json!({
        "type": "debug_variables",
        "session_id": session_id,
        "variables_reference": variables_reference,
        "start": start,
        "count": count,
        "filter": filter,
        "child_count": summary.len(),
        "drillable_count": drillable_count,
        "variables": summary,
    }))
}

