//! `.theo/theo.md` auto-initialization. Extracted from `run_engine.rs`
//! (Fase 4 — REMEDIATION_PLAN T4.2) to isolate filesystem-touching
//! bootstrap logic from the hot main loop.
//!
//! The template is intentionally static — the agent enriches it later.
//! All writes are best-effort; failures surface via
//! `crate::fs_errors::warn_fs_error` but never abort the caller.

use std::path::Path;

/// Ensure `.theo/theo.md` exists with a static template. Best-effort,
/// never fails loud. Creates `.theo/.gitignore` alongside if missing.
pub(crate) fn auto_init_project_context(project_dir: &Path) {
    let theo_md = project_dir.join(".theo").join("theo.md");
    if theo_md.exists() {
        return;
    }

    // Detect project type for template
    let lang = detect_project_lang(project_dir);

    // Detect project name (first line with name= in manifest)
    let name = detect_project_name_simple(project_dir).unwrap_or_else(|| {
        project_dir
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("project")
            .to_string()
    });

    let content = build_theo_md_template(project_dir, &name, lang);

    let theo_dir = project_dir.join(".theo");
    if let Err(e) = std::fs::create_dir_all(&theo_dir) {
        crate::fs_errors::warn_fs_error("auto_init/theo_mkdir", &theo_dir, &e);
        return;
    }
    if let Err(e) = std::fs::write(&theo_md, content) {
        crate::fs_errors::warn_fs_error("auto_init/theo_md_write", &theo_md, &e);
    }

    // Also create .gitignore if missing.
    let gitignore = theo_dir.join(".gitignore");
    if !gitignore.exists()
        && let Err(e) = std::fs::write(
            &gitignore,
            "# Generated by Theo\ngraph.bin\ngraph.bin.tmp\nlearnings.json\nsnapshots/\nsessions/\n",
        )
    {
        crate::fs_errors::warn_fs_error("auto_init/gitignore_write", &gitignore, &e);
    }

    eprintln!("[theo] Auto-initialized .theo/theo.md — run `theo init` for detailed context");
}

fn detect_project_lang(project_dir: &Path) -> &'static str {
    if project_dir.join("Cargo.toml").exists() {
        "Rust"
    } else if project_dir.join("package.json").exists() {
        "Node.js / TypeScript"
    } else if project_dir.join("pyproject.toml").exists() {
        "Python"
    } else if project_dir.join("go.mod").exists() {
        "Go"
    } else {
        "Unknown"
    }
}

fn build_theo_md_template(project_dir: &Path, name: &str, lang: &str) -> String {
    let mut sections = Vec::new();
    sections.push(format!("# {name}\n"));
    sections.push(format!("## Language\n{lang}\n"));

    let has_docs = project_dir.join("docs").exists();
    let has_readme = project_dir.join("README.md").exists();
    let has_adr = project_dir.join("docs").join("adr").exists();

    sections.push("## Architecture\n".to_string());
    if has_readme {
        sections.push("See `README.md` for project overview.\n".to_string());
    }
    if has_docs {
        sections.push("See `docs/` for detailed documentation.\n".to_string());
    }
    if has_adr {
        sections.push("See `docs/adr/` for Architecture Decision Records.\n".to_string());
    }
    if !has_readme && !has_docs {
        sections
            .push("<!-- Run `theo init` to generate detailed project context -->\n".to_string());
    }

    sections.push("## Key Files\n".to_string());
    let key_files = [
        ("Cargo.toml", "Rust workspace manifest"),
        ("package.json", "Node.js package config"),
        ("pyproject.toml", "Python project config"),
        ("go.mod", "Go module config"),
        (".github/workflows", "CI/CD pipelines"),
    ];
    for (file, desc) in &key_files {
        if project_dir.join(file).exists() {
            sections.push(format!("- `{file}` — {desc}\n"));
        }
    }

    sections.join("")
}

/// Simple project name detection (no external deps). Tries `Cargo.toml`
/// then `package.json` and returns the first `name = "..."` found.
pub(crate) fn detect_project_name_simple(project_dir: &Path) -> Option<String> {
    if let Ok(content) = std::fs::read_to_string(project_dir.join("Cargo.toml")) {
        for line in content.lines() {
            let t = line.trim();
            if t.starts_with("name")
                && t.contains('=')
                && let Some(val) = t.split('=').nth(1)
            {
                let name = val.trim().trim_matches('"').trim_matches('\'');
                if !name.is_empty() {
                    return Some(name.to_string());
                }
            }
        }
    }
    if let Ok(content) = std::fs::read_to_string(project_dir.join("package.json")) {
        for line in content.lines() {
            let t = line.trim().trim_start_matches('{').trim();
            if t.starts_with("\"name\"")
                && let Some(val) = t.split(':').nth(1)
            {
                let name = val
                    .trim()
                    .trim_end_matches('}')
                    .trim_matches(',')
                    .trim()
                    .trim_matches('"');
                if !name.is_empty() {
                    return Some(name.to_string());
                }
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::tempdir;

    #[test]
    fn detect_project_lang_rust() {
        let d = tempdir().unwrap();
        fs::write(d.path().join("Cargo.toml"), "[package]\nname=\"x\"\n").unwrap();
        assert_eq!(detect_project_lang(d.path()), "Rust");
    }

    #[test]
    fn detect_project_lang_unknown_for_empty_dir() {
        let d = tempdir().unwrap();
        assert_eq!(detect_project_lang(d.path()), "Unknown");
    }

    #[test]
    fn detect_project_name_from_cargo_toml() {
        let d = tempdir().unwrap();
        fs::write(
            d.path().join("Cargo.toml"),
            "[package]\nname = \"my-crate\"\n",
        )
        .unwrap();
        assert_eq!(
            detect_project_name_simple(d.path()).as_deref(),
            Some("my-crate")
        );
    }

    #[test]
    fn detect_project_name_from_package_json() {
        let d = tempdir().unwrap();
        // Multi-line JSON — the parser is intentionally line-based and
        // does not handle single-line JSON with multiple colons per line.
        fs::write(
            d.path().join("package.json"),
            "{\n  \"name\": \"pkg\",\n  \"version\": \"1.0.0\"\n}\n",
        )
        .unwrap();
        assert_eq!(detect_project_name_simple(d.path()).as_deref(), Some("pkg"));
    }

    #[test]
    fn detect_project_name_none_when_no_manifest() {
        let d = tempdir().unwrap();
        assert_eq!(detect_project_name_simple(d.path()), None);
    }

    #[test]
    fn auto_init_creates_theo_md_when_missing() {
        let d = tempdir().unwrap();
        fs::write(d.path().join("Cargo.toml"), "[package]\nname=\"x\"\n").unwrap();
        auto_init_project_context(d.path());
        assert!(d.path().join(".theo").join("theo.md").exists());
    }

    #[test]
    fn auto_init_skips_when_theo_md_exists() {
        let d = tempdir().unwrap();
        fs::create_dir_all(d.path().join(".theo")).unwrap();
        fs::write(d.path().join(".theo/theo.md"), "# preserve me\n").unwrap();
        auto_init_project_context(d.path());
        let content = fs::read_to_string(d.path().join(".theo/theo.md")).unwrap();
        assert_eq!(content, "# preserve me\n");
    }
}
