//! Single-purpose slice extracted from `graph_context_service.rs` (T4.5 of god-files-2026-07-23-plan.md, ADR D5).

#![allow(unused_imports, dead_code)]

use std::collections::BTreeMap;
use std::path::Path;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::{Duration, SystemTime};

use theo_domain::graph_context::{
    ContextBlock, GraphContextError, GraphContextProvider, GraphContextResult,
};

use theo_engine_graph::bridge::{
    self, DataModelData, FileData, ImportData, ReferenceData, SymbolData,
};
use theo_engine_graph::cluster::{ClusterAlgorithm, ClusterResult, Community};
use theo_engine_graph::model::CodeGraph;

use theo_engine_parser::tree_sitter::{self as ts, SupportedLanguage};
use theo_engine_parser::types::FileExtraction;

use theo_engine_retrieval::assembly;
use theo_engine_retrieval::search::FileBm25;
#[cfg(not(feature = "tantivy-backend"))]
use theo_engine_retrieval::search::MultiSignalScorer;

#[cfg(feature = "tantivy-backend")]
use theo_engine_retrieval::tantivy_search::FileTantivyIndex;

#[cfg(feature = "dense-retrieval")]
use theo_engine_retrieval::embedding::cache::EmbeddingCache;
#[cfg(feature = "dense-retrieval")]
use theo_engine_retrieval::embedding::neural::NeuralEmbedder;
#[cfg(feature = "dense-retrieval")]
use theo_engine_retrieval::pipeline::retrieve_with_config;
// T8.1 — `CrossEncoderConfig` + `CrossEncoderReranker` are always
// compiled by the retrieval crate, but we only consume them on the
// dense-retrieval path because that's where the RRF candidate set
// originates.
#[cfg(feature = "dense-retrieval")]
use theo_engine_retrieval::reranker::{CrossEncoderConfig, CrossEncoderReranker};

/// T8.1 part 4 — Read `THEO_RERANKER_PRELOAD` from the environment.
/// Truthy (`1`, `true`, `yes`, `on`, case-insensitive) opts the
/// background graph build into preloading the cross-encoder model
/// — first session pays the ~200 MB download once; subsequent
/// queries get the +15 pt nDCG@10 SOTA gain immediately.
/// Falsy / unset = preload OFF (default; preserves cold-start speed
/// for users who don't query enough to amortize the download).
use super::*;

pub fn write_back_to_wiki(
    cache_dir: &Path,
    query: &str,
    blocks: &[ContextBlock],
) -> std::io::Result<()> {
    std::fs::create_dir_all(cache_dir)?;

    // Slug from query (deterministic)
    let slug: String = query
        .to_lowercase()
        .split_whitespace()
        .take(5)
        .collect::<Vec<_>>()
        .join("-")
        .replace(|c: char| !c.is_alphanumeric() && c != '-', "");

    if slug.is_empty() {
        return Ok(());
    }

    let path = cache_dir.join(format!("{}.md", slug));

    // Load current graph_hash for staleness tracking
    let graph_hash = cache_dir
        .parent()
        .and_then(|wiki_dir| wiki_dir.parent().and_then(|p| p.parent()))
        .and_then(|project_dir| {
            theo_engine_retrieval::wiki::persistence::load_manifest(project_dir)
        })
        .map(|m| m.graph_hash)
        .unwrap_or(0);

    // Check staleness: overwrite if existing page has different graph_hash
    if path.exists()
        && let Ok(existing) = std::fs::read_to_string(&path) {
            let fm = theo_engine_retrieval::wiki::model::parse_frontmatter(&existing);
            if let Some(existing_hash) = fm.graph_hash {
                if existing_hash == graph_hash {
                    return Ok(()); // Fresh — skip
                }
                // Stale — will overwrite below
            } else {
                return Ok(()); // Legacy page without frontmatter — don't overwrite
            }
        }

    // Build formatted markdown page with canonical frontmatter
    let fm = theo_engine_retrieval::wiki::model::PageFrontmatter::cache(query, graph_hash);
    let mut md = theo_engine_retrieval::wiki::model::render_frontmatter(&fm);

    md += &format!("# Query: {}\n\n", query);
    md += &format!(
        "> Cached from GRAPHCTX pipeline | {} results\n\n",
        blocks.len()
    );

    // Relevant files table
    md += "## Relevant Files\n\n";
    md += "| File | Score |\n|------|-------|\n";
    for block in blocks {
        let score_str = format!("{:.2}", block.score);
        md += &format!("| `{}` | {} |\n", block.source_id, score_str);
    }
    md += "\n";

    // Code context from each block
    md += "## Context\n\n";
    for block in blocks {
        let preview: String = block
            .content
            .lines()
            .take(20)
            .collect::<Vec<_>>()
            .join("\n");
        md += &format!("### {}\n\n{}\n\n", block.source_id, preview);
    }

    md += "---\n";
    md += &format!(
        "*Generated by GRAPHCTX | {} blocks, {:.0} tokens*\n",
        blocks.len(),
        blocks.iter().map(|b| b.token_count as f64).sum::<f64>()
    );

    std::fs::write(&path, md)?;

    // Log the write-back
    if let Some(wiki_dir) = cache_dir.parent()
        && let Some(project_dir) = wiki_dir.parent().and_then(|p| p.parent()) {
            theo_engine_retrieval::wiki::persistence::append_log(
                project_dir,
                "query",
                &format!("Cached result for: {} ({} blocks)", query, blocks.len()),
            );
        }

    Ok(())
}

// parse_frontmatter_graph_hash removed — use theo_engine_retrieval::wiki::model::parse_frontmatter()

pub fn generate_wiki_if_stale(graph: &CodeGraph, communities: &[Community], project_dir: &Path) {
    use theo_engine_retrieval::wiki;

    let hash = wiki::generator::compute_graph_hash(graph);
    if wiki::persistence::is_fresh(project_dir, hash) {
        return; // Wiki is up-to-date
    }

    let project_name = project_dir
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("project");

    // Load or create wiki schema
    let schema = wiki::persistence::load_schema(project_dir, project_name);
    let _ = wiki::persistence::write_schema_default(project_dir, &schema);

    // Try incremental generation first
    let existing_manifest = wiki::persistence::load_manifest(project_dir);
    let (wiki_data, log_detail) = if let Some(manifest) = &existing_manifest {
        if !manifest.page_hashes.is_empty() {
            // Load existing docs from disk for incremental merge
            let existing_docs = wiki::generator::generate_wiki(communities, graph, project_name);
            let (wiki, stats) = wiki::generator::generate_wiki_incremental(
                communities,
                graph,
                project_name,
                manifest,
                &existing_docs.docs,
            );
            let detail = format!("incremental | {}", stats);
            (wiki, detail)
        } else {
            // Old manifest without page_hashes → full regen
            let wiki = wiki::generator::generate_wiki(communities, graph, project_name);
            let detail = format!("full | {} pages from graph", wiki.docs.len());
            (wiki, detail)
        }
    } else {
        let wiki = wiki::generator::generate_wiki(communities, graph, project_name);
        let detail = format!("initial | {} pages from graph", wiki.docs.len());
        (wiki, detail)
    };

    // Cleanup orphaned pages before writing
    let wiki_dir = project_dir.join(".theo").join("wiki");
    let current_slugs: std::collections::HashSet<String> =
        wiki_data.docs.iter().map(|d| d.slug.clone()).collect();
    let removed = wiki::persistence::cleanup_orphaned_pages(&wiki_dir, &current_slugs);
    if removed > 0 {
        eprintln!("[wiki] Cleaned up {} orphaned pages", removed);
    }

    if let Err(e) = wiki::persistence::write_to_disk(&wiki_data, project_dir) {
        eprintln!("[wiki] Warning: failed to write wiki: {e}");
    } else {
        eprintln!(
            "[wiki] Generated {} pages in .theo/wiki/ ({})",
            wiki_data.docs.len(),
            log_detail
        );
        wiki::persistence::append_log(project_dir, "ingest", &log_detail);

        // Cache lifecycle: mark stale, GC cold (7 days)
        let stale_moved = wiki::persistence::mark_stale_cache(&wiki_dir, hash);
        let gc_removed = wiki::persistence::gc_cold_cache(&wiki_dir, 604800); // 7 days
        if stale_moved > 0 || gc_removed > 0 {
            eprintln!(
                "[wiki] Cache lifecycle: {} marked stale, {} GC'd",
                stale_moved, gc_removed
            );
        }
    }
}
